-- AlterTable
ALTER TABLE "Organization" ADD COLUMN     "accrualRatePerPeriod" DOUBLE PRECISION,
ADD COLUMN     "autoLunchDeductOnce" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "autoLunchEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "autoLunchIgnoreIfBreak" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "autoLunchMinimumShift" DOUBLE PRECISION NOT NULL DEFAULT 6.0,
ADD COLUMN     "autoLunchMinutes" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "biweeklyAnchorDate" TIMESTAMP(3),
ADD COLUMN     "carryoverEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "carryoverLimit" DOUBLE PRECISION,
ADD COLUMN     "cutoffTime" TEXT DEFAULT '17:00',
ADD COLUMN     "doubleTimeEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "doubletimeDailyThresholdHours" DOUBLE PRECISION NOT NULL DEFAULT 12.0,
ADD COLUMN     "maxPtoBalance" DOUBLE PRECISION,
ADD COLUMN     "overtimeDailyEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "overtimeDailyThresholdHours" DOUBLE PRECISION NOT NULL DEFAULT 8.0,
ADD COLUMN     "overtimeWeeklyEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "overtimeWeeklyThresholdHours" DOUBLE PRECISION NOT NULL DEFAULT 40.0,
ADD COLUMN     "payPeriodType" "PayPeriodType" NOT NULL DEFAULT 'WEEKLY',
ADD COLUMN     "phone" TEXT,
ADD COLUMN     "ptoEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "weekStartDay" INTEGER NOT NULL DEFAULT 1,
ALTER COLUMN "timezone" SET DEFAULT 'America/New_York';
